spring: 
  profiles: 
    active: local
--- 
spring: 
  profiles: prod 
  datasource:
      driver-class-name: org.postgresql.Driver 
      username: postgres
      password: infodba
      url: jdbc:postgresql//122.44.15.249:35432/Chat
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate.ddl-auto : none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
--- 
spring: 
  profiles: local 
  datasource: 
      driver-class-name: org.postgresql.Driver  
      username: infodba 
      password: infodba 
      url: jdbc:postgresql://localhost/Chat
  jpa:  
    show-sql: true  
    hibernate.ddl-auto : none 
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      
--- 
 spring:
  jackson:
    serialization:
      fail-on-empty-beans: false